networks:
  b2c:
volumes:
  shared-volume:
services:
  grpc_server:
    build: ./streaming
    # dockerfile: ./grpc_server/Dockerfile
    # container_name: grpc_server
    # restart: always
    ports:
      - "5001:5001"
    networks:
      - b2c
    volumes:
      - shared-volume:/shared

  grpc_client:
    build: ./api
    # dockerfile: ./grpc_client/Dockerfile
    # container_name: grpc_client
    # restart: always
    environment:
      - RTSP_SERVER=grpc_server:5001
      # - RTSP_URL=rtsp://rtspstream:07451b4ef79b34a8473a745fd99a50es0@zephyr.rtsp.stream/movie
      - RTSP_URL=rtsp://host.docker.internal:8554/mystream
    ports:
      - "5000:3000"
    networks:
      - b2c
    volumes:
      - shared-volume:/shared
    depends_on:
      - grpc_server
