# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: streaming.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstreaming.proto\"/\n\nStreamInfo\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\r\n\x05media\x18\x02 \x01(\t\"h\n\x0bStreamState\x12!\n\x05state\x18\x02 \x01(\x0e\x32\x12.StreamState.State\"6\n\x05State\x12\r\n\tUNDEFINED\x10\x00\x12\x07\n\x03NEW\x10\x01\x12\n\n\x06\x41\x43TIVE\x10\x06\x12\t\n\x05\x45NDED\x10\x07\"\x1c\n\rStreamRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"m\n\x0eStreamResponse\x12\"\n\x0bstream_info\x18\x01 \x01(\x0b\x32\x0b.StreamInfoH\x00\x12$\n\x0cstream_state\x18\x02 \x01(\x0b\x32\x0c.StreamStateH\x00\x42\x11\n\x0fstream_response2A\n\tStreaming\x12\x34\n\rStreamingRTSP\x12\x0e.StreamRequest\x1a\x0f.StreamResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMINFO']._serialized_start=19
  _globals['_STREAMINFO']._serialized_end=66
  _globals['_STREAMSTATE']._serialized_start=68
  _globals['_STREAMSTATE']._serialized_end=172
  _globals['_STREAMSTATE_STATE']._serialized_start=118
  _globals['_STREAMSTATE_STATE']._serialized_end=172
  _globals['_STREAMREQUEST']._serialized_start=174
  _globals['_STREAMREQUEST']._serialized_end=202
  _globals['_STREAMRESPONSE']._serialized_start=204
  _globals['_STREAMRESPONSE']._serialized_end=313
  _globals['_STREAMING']._serialized_start=315
  _globals['_STREAMING']._serialized_end=380
# @@protoc_insertion_point(module_scope)
