# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: authentication.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'authentication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61uthentication.proto\x12\x0e\x61uthentication\"\x82\x01\n\x14\x41uthenticationResult\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x14\n\x0c_createdDate\x18\x05 \x01(\t\x12\x0b\n\x03iat\x18\x06 \x01(\x03\x12\x0b\n\x03\x65xp\x18\x07 \x01(\x03\"&\n\x15\x41uthenticationRequest\x12\r\n\x05token\x18\x01 \x01(\t\"p\n\x16\x41uthenticationResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x34\n\x06result\x18\x03 \x01(\x0b\x32$.authentication.AuthenticationResult2w\n\x15\x41uthenticationService\x12^\n\rvalidateToken\x12%.authentication.AuthenticationRequest\x1a&.authentication.AuthenticationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'authentication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHENTICATIONRESULT']._serialized_start=41
  _globals['_AUTHENTICATIONRESULT']._serialized_end=171
  _globals['_AUTHENTICATIONREQUEST']._serialized_start=173
  _globals['_AUTHENTICATIONREQUEST']._serialized_end=211
  _globals['_AUTHENTICATIONRESPONSE']._serialized_start=213
  _globals['_AUTHENTICATIONRESPONSE']._serialized_end=325
  _globals['_AUTHENTICATIONSERVICE']._serialized_start=327
  _globals['_AUTHENTICATIONSERVICE']._serialized_end=446
# @@protoc_insertion_point(module_scope)
