# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: store.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'store.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstore.proto\x12\x05store\"U\n\x0cStoreRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\x12\x10\n\x08rawImage\x18\x03 \x01(\x0c\x12\x16\n\x0epredictedImage\x18\x04 \x01(\x0c\"1\n\rStoreResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\"q\n\x12StoreReportRequest\x12\x10\n\x08streamId\x18\x01 \x01(\t\x12\x0e\n\x06userId\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x15\n\risFrameStored\x18\x05 \x01(\x08\"G\n\x13StoreReportResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0e\n\x06result\x18\x03 \x01(\t2\x95\x01\n\x0cStoreService\x12<\n\rtemporarySave\x12\x13.store.StoreRequest\x1a\x14.store.StoreResponse\"\x00\x12G\n\x0c\x63reateReport\x12\x19.store.StoreReportRequest\x1a\x1a.store.StoreReportResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'store_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOREREQUEST']._serialized_start=22
  _globals['_STOREREQUEST']._serialized_end=107
  _globals['_STORERESPONSE']._serialized_start=109
  _globals['_STORERESPONSE']._serialized_end=158
  _globals['_STOREREPORTREQUEST']._serialized_start=160
  _globals['_STOREREPORTREQUEST']._serialized_end=273
  _globals['_STOREREPORTRESPONSE']._serialized_start=275
  _globals['_STOREREPORTRESPONSE']._serialized_end=346
  _globals['_STORESERVICE']._serialized_start=349
  _globals['_STORESERVICE']._serialized_end=498
# @@protoc_insertion_point(module_scope)
