# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: store.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'store.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstore.proto\x12\x05store\"!\n\x0cStoreRequest\x12\x11\n\treport_id\x18\x01 \x01(\t\"1\n\rStoreResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32I\n\x0cStoreService\x12\x39\n\nsaveReport\x12\x13.store.StoreRequest\x1a\x14.store.StoreResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'store_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOREREQUEST']._serialized_start=22
  _globals['_STOREREQUEST']._serialized_end=55
  _globals['_STORERESPONSE']._serialized_start=57
  _globals['_STORERESPONSE']._serialized_end=106
  _globals['_STORESERVICE']._serialized_start=108
  _globals['_STORESERVICE']._serialized_end=181
# @@protoc_insertion_point(module_scope)
