# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stream.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cstream.proto\x12\x06stream\"!\n\rStreamRequest\x12\x10\n\x08streamId\x18\x01 \x01(\t\"\"\n\x13StreamCreateRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"B\n\x0eStreamResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0e\n\x06result\x18\x03 \x01(\t2\x90\x01\n\rStreamService\x12\x43\n\x0c\x63reateStream\x12\x1b.stream.StreamCreateRequest\x1a\x16.stream.StreamResponse\x12:\n\tgetStream\x12\x15.stream.StreamRequest\x1a\x16.stream.StreamResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMREQUEST']._serialized_start=24
  _globals['_STREAMREQUEST']._serialized_end=57
  _globals['_STREAMCREATEREQUEST']._serialized_start=59
  _globals['_STREAMCREATEREQUEST']._serialized_end=93
  _globals['_STREAMRESPONSE']._serialized_start=95
  _globals['_STREAMRESPONSE']._serialized_end=161
  _globals['_STREAMSERVICE']._serialized_start=164
  _globals['_STREAMSERVICE']._serialized_end=308
# @@protoc_insertion_point(module_scope)
