# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: video_streaming.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'video_streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15video_streaming.proto\x12\x0evideoStreaming\"f\n\x13StreamResponseModel\x12$\n\x05state\x18\x01 \x01(\x0e\x32\x15.videoStreaming.State\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x0b\n\x03raw\x18\x04 \x01(\x0c\"\x1c\n\rStreamRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"D\n\x0eStreamResponse\x12$\n\x05state\x18\x01 \x01(\x0e\x32\x15.videoStreaming.State\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c*C\n\x05State\x12\x10\n\x0cINITIALIZING\x10\x00\x12\x0e\n\nPROCESSING\x10\x01\x12\r\n\tCOMPLETED\x10\x02\x12\t\n\x05\x45RROR\x10\x03\x32\xb6\x01\n\x0eVideoStreaming\x12L\n\tgetStream\x12\x1d.videoStreaming.StreamRequest\x1a\x1e.videoStreaming.StreamResponse0\x01\x12V\n\x0egetStreamModel\x12\x1d.videoStreaming.StreamRequest\x1a#.videoStreaming.StreamResponseModel0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATE']._serialized_start=245
  _globals['_STATE']._serialized_end=312
  _globals['_STREAMRESPONSEMODEL']._serialized_start=41
  _globals['_STREAMRESPONSEMODEL']._serialized_end=143
  _globals['_STREAMREQUEST']._serialized_start=145
  _globals['_STREAMREQUEST']._serialized_end=173
  _globals['_STREAMRESPONSE']._serialized_start=175
  _globals['_STREAMRESPONSE']._serialized_end=243
  _globals['_VIDEOSTREAMING']._serialized_start=315
  _globals['_VIDEOSTREAMING']._serialized_end=497
# @@protoc_insertion_point(module_scope)
