# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import video_streaming_pb2 as video__streaming__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in video_streaming_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VideoStreamingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getStream = channel.unary_stream(
                '/videoStreaming.VideoStreaming/getStream',
                request_serializer=video__streaming__pb2.StreamRequest.SerializeToString,
                response_deserializer=video__streaming__pb2.StreamResponse.FromString,
                _registered_method=True)
        self.getStreamModel = channel.unary_stream(
                '/videoStreaming.VideoStreaming/getStreamModel',
                request_serializer=video__streaming__pb2.StreamRequest.SerializeToString,
                response_deserializer=video__streaming__pb2.StreamResponseModel.FromString,
                _registered_method=True)


class VideoStreamingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getStreamModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoStreamingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getStream': grpc.unary_stream_rpc_method_handler(
                    servicer.getStream,
                    request_deserializer=video__streaming__pb2.StreamRequest.FromString,
                    response_serializer=video__streaming__pb2.StreamResponse.SerializeToString,
            ),
            'getStreamModel': grpc.unary_stream_rpc_method_handler(
                    servicer.getStreamModel,
                    request_deserializer=video__streaming__pb2.StreamRequest.FromString,
                    response_serializer=video__streaming__pb2.StreamResponseModel.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'videoStreaming.VideoStreaming', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('videoStreaming.VideoStreaming', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VideoStreaming(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/videoStreaming.VideoStreaming/getStream',
            video__streaming__pb2.StreamRequest.SerializeToString,
            video__streaming__pb2.StreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getStreamModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/videoStreaming.VideoStreaming/getStreamModel',
            video__streaming__pb2.StreamRequest.SerializeToString,
            video__streaming__pb2.StreamResponseModel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
